title: Senior Forge Codex
tagline: >-
  The definitive reference for the path to Android Seniority. / La referencia definitiva hacia el seniority en Android.
description: >-
  The Senior Forge Codex: The Path to Seniority. A technical reference manual for Senior Android Developer interviews.

url: 'https://aghmnl.github.io' # Replace with your actual URL
baseurl: ''

author: aghmnl
github_username: aghmnl

theme: jekyll-theme-chirpy

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: "en"
    values:
      lang: en
  - scope:
      path: "es"
    values:
      lang: es

# Chirpy Specific Configuration
# (Add more as needed, but this is a base start)
timezone: UTC
lang: en # default language
