title: The Senior Forge Codex
tagline: A technical reference manual for Senior Android Developer interviews.
description: >-
  A compendium of theoretical topics serving as a reference for The Senior Forge articles on the journey to seniority.
  Maintained by aghmnl.

url: 'https://aghmnl.github.io' # Replace with your actual URL
baseurl: ''

author: aghmnl
github_username: aghmnl

theme: jekyll-theme-chirpy

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: "en"
    values:
      lang: en
  - scope:
      path: "es"
    values:
      lang: es

# Chirpy Specific Configuration
# (Add more as needed, but this is a base start)
timezone: UTC
lang: en # default language
