title: The Senior Forge Codex
description: A compendium of theoretical topics serving as a reference for The Senior Forge articles on the journey to seniority.
remote_theme: jekyll/jekyll-theme-midnight
baseurl: ""
url: ""

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: "en"
    values:
      lang: en
      layout: default
  - scope:
      path: "es"
    values:
      lang: es
      layout: default

# Exclusion list
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .jekyll-cache
  - .sass-cache
  - .jekyll-metadata
